version: 0.0
os: linux
files:
  - source: html/
    destination: /var/lib/tomcat8/webapps/ROOT/
hooks:
  ApplicationStop:
    - location: scripts/stop_tomcat8.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_tomcat8.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/verify_tomcat8.sh
      timeout: 300
      runas: root